### ISSUE TITLE
Enable RLS

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/text-vector-embeddings#2]
The database can be accessed by anyone public with a full read / write access, which raises security concerns. RLS should be enabled on all the tables and a token required to modify data.

**Comment by 0x4007** [comment]
It would be nice to do git based storage but not sure if it is feasible for vectors given the amount of data that needs to be saved.

**Comment by sshivaditya2019** [comment]
I can work on this. Are you trying to 

> The database can be accessed by anyone public with a full read / write access, which raises security concerns. RLS should be enabled on all the tables and a token required to modify data.

I can work on this. Are you looking to allow write access with `user_role` ? or more like authenticated user with supabase ?

**Comment by sshivaditya2019** [comment]
> It would be nice to do git based storage but not sure if it is feasible for vectors given the amount of data that needs to be saved.
I just made some rough calculations, we could create a repository with sqlite and store close to 150,000 entries with the same schema as the supabase one. This is assuming Git-LFS has a free plan limit of 2GB.

**Comment by 0x4007** [comment]
Assuming on average 50 comments daily, we get a bit over 8 years of storage. Perhaps git based storage is a good idea!

**Comment by sshivaditya2019** [comment]
> > I can work on this. Are you looking to allow write access with `user_role` ? or more like authenticated user with supabase ?
> 
> Does anybody have a rough time estimate for this project?
> 
That should depend on how fine grained you want the control on write-access.
> > I just made some rough calculations, we could create a repository with sqlite and store close to 150,000 entries with the same schema as the supabase one. This is assuming Git-LFS has a free plan limit of 2GB.
> 
> Assuming on average 50 comments daily, we get a bit over 8 years of storage. Perhaps git based storage is a good idea!
The Data Update and Data Creation would be hassle. So, application would require an in-memory staging database, after certain number of commits, they would forward the changes to the db.

**Comment by 0x4007** [comment]
@gentlementlegen or @rndquu perhaps you can add a time estimate.

**Comment by gentlementlegen** [comment]
@rndquu The project is running in a separate Supabase instance, I can give you access if you need to.

Yes this can be closed.

**Comment by Keyrxng** [comment]
> @rndquu The project is running in a separate Supabase instance, I can give you access if you need to.
> 
> Yes this can be closed.

I'll need those details to integrate into `telegram-kernel` as it also uses the embeddings db. (currently mine)

**Comment by gentlementlegen** [comment]
@Keyrxng poke me with your supabase email to add you.
