### ISSUE TITLE
Scraper: Populate "Closed As Complete" Issue Specifications

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/text-vector-embeddings#56]
We need to populate our matchmaking database. We "register" users in our system when they "Sign in with GitHub" on https://devpool.directory/

I suppose with GraphQL it may be simple to check every issue that is closed as complete with these assignees. 

- We need to capture all of the metadata to make it easier to work with later.
- We need to be able to determine the location of the issue, which means organization and repository. We should capture both the names as well as the IDs, in case of renames. 
- We need to generate vector embeddings and store the specifications in plain text. 

For now we can work off of a static snapshot of registrants. In the future, we should automatically scrape their completed issues as soon as they register on our site. 

[auth.users.json](https://github.com/user-attachments/files/18005367/auth.users.json)
[auth.users.csv](https://github.com/user-attachments/files/18005368/auth.users.csv)

**Comment by 0x4007** [comment]
Unfortunately, it has to be done manually because it's in a different organization and that's difficult to do from my iPhone

**Comment by 0x4007** [comment]
> @0x4007 Should this be moved to work.ubq.fi instead of keeping it here? We can make GraphQL queries directly with the access token that we receive. I think the current scopes should be enough, unless we plan to target private repos.

I think this is more focused on building the core scraper logic and then later we can connect it to the registration/login logic as a separate task.

**Comment by 0x4007** [comment]
I think this can be manually run for now. Otherwise it should be on registration at the directory.

**Comment by 0x4007** [comment]
> 
>       
> > [!WARNING]
> > You have reached your max task limit. Please close out some tasks before assigning new ones.
> 
> 
> 
> 

This response doesn't make sense @gentlementlegen any ideas

**Comment by gentlementlegen** [comment]
@0x4007 Why are there many comments without anything in between, are you deleting comments?

**Comment by 0x4007** [comment]
No. Besides it would clearly show on the timeline if any comments are deleted unless they are my own.

**Comment by gentlementlegen** [comment]
The start attempts seems to be from @sshivaditya2019 don't know why the comments are deleted. The reason why there is no linked task in the comment is that the linked pull-requests failed to get fetched:
```
[2m	› [2m  ↳  getAllPullRequests (index.js:55204:11)
	    ↳  async getAllPullRequestsWithRetry (index.js:55210:12)
	    ↳  async getPendingOpenedPullRequests (index.js:55289:30)
	    ↳  async handleTaskLimitChecks (index.js:55876:30)
	    ↳  async start (index.js:55774:39)
	    ↳  async userPullRequest (index.js:56029:16)
	    ↳  async startStopTask (index.js:56105:14)
	    ↳  async Array.<anonymous> (index.js:47646:22)[0m[0m
```

First attempt fails because the account is private, the second one doesn't give any details about the failure, but it is probably the same.

**Comment by 0x4007** [comment]
@sshivaditya2019 please make an issue in the appropriate report and address

**Comment by 0x4007** [comment]
So what's next steps here? What is the solution @gentlementlegen @sshivaditya2019

**Comment by gentlementlegen** [comment]
@sshivaditya2019 If I understand properly, these happened when you linked https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/59 correct?

It would make sense because the bot will try to assign you to this task. Then, it checks your PR quota which you are above but can't list the linked pull-requests because your profile is private. So you just get the warning here. Not sure what can be done about it.

**Comment by 0x4007** [comment]
> @sshivaditya2019 If I understand properly, these happened when you linked https://github.com/ubiquity-os-marketplace/text-vector-embeddings/pull/59 correct?
> 
> 
> 
> It would make sense because the bot will try to assign you to this task. Then, it checks your PR quota which you are above but can't list the linked pull-requests because your profile is private. So you just get the warning here. Not sure what can be done about it.

A short term workaround:

If this error is caught, then comment a descriptive warning explaining the situation and how to fix it.

**Comment by 0x4007** [comment]
Relevance scoring could have done so much better here for you @gentlementlegen 

Perhaps this conversation should be saved as a unit test of sorts so that we can improve the relevance scoring prompt

**Comment by gentlementlegen** [comment]
Sure you can try playing with the settings to adjust it through the UI in text-conversation-rewards
