### ISSUE TITLE
Issue Matching Fails, with invalid payload object.

### ISSUE THREAD

**Issue by sshivaditya2019** [ubiquity-os-marketplace/text-vector-embeddings#60]
The issue matchmaking (issue contributor recommendation) functionality should work across multiple orgs/repos and not be restricted within single repo.

**Comment by 0x4007** [comment]
> The issue matching functionality

This isn't specific enough please be careful to use precise terminology. 

Is this for issue deduplication or is this for talent recommendation?

**Comment by 0x4007** [comment]
> ```diff
> ! You are not allowed to generate permits.
> ```

@gentlementlegen sshivaditya2019 is a collaborator

**Comment by gentlementlegen** [comment]
I know that the profile is private so probably the bot cannot see the collaborator status.
