### ISSUE TITLE
Issue Deduplication Breaking Link

### ISSUE THREAD

**Issue by sshivaditya2019** [ubiquity-os-marketplace/text-vector-embeddings#64]
![image](https://github.com/user-attachments/assets/af9b8e16-36bb-48cf-92e3-ae76f9f936d1)

@sshivaditya2019 please fix this

_Originally posted by @0x4007 in https://github.com/ubiquity-os-marketplace/command-start-stop/issues/103#issuecomment-2541004633_

**Comment by 0x4007** [comment]
I just made you an administrator so you should be able to generate permits now
